# Generated by Django 5.2.4 on 2025-12-04 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_category_branch_branch_manager_branch_branch_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='restaurants.restaurant'),
        ),
    ]
